[package]
name = "clickhouse-experiment"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
clickhouse = { version = "0.14", features = ["lz4"] }
fake = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.0", features = ["serde", "v4"] }
